///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace git_jenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the git_jenkinsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("78097179-a780-4911-8422-d30b16264115")]
    public partial class git_jenkinsRepository : RepoGenBaseFolder
    {
        static git_jenkinsRepository instance = new git_jenkinsRepository();
        git_jenkinsRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the git_jenkinsRepository element repository.
        /// </summary>
        [RepositoryFolder("78097179-a780-4911-8422-d30b16264115")]
        public static git_jenkinsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public git_jenkinsRepository() 
            : base("git_jenkinsRepository", "/", null, 0, false, "78097179-a780-4911-8422-d30b16264115", ".\\RepositoryImages\\git_jenkinsRepository78097179.rximgres")
        {
            _rxmainframe = new git_jenkinsRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("78097179-a780-4911-8422-d30b16264115")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("128da318-9aeb-4bbc-9f57-07cc8498df12")]
        public virtual git_jenkinsRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class git_jenkinsRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("128da318-9aeb-4bbc-9f57-07cc8498df12")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _rxtabintroductionInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@automationid='RxMainFrame']", parentFolder, 30000, null, true, "128da318-9aeb-4bbc-9f57-07cc8498df12", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/tabpage[@automationid='RxTabIntroduction']/?/?/text[@accessiblename='Enter your name']", ".//text[@accessiblename='Enter your name']", 30000, null, "f273fc3e-9801-4934-80a1-0890d27339d9");
                _rxtabintroductionInfo = new RepoItemInfo(this, "RxTabIntroduction", "?/?/tabpage[@automationid='RxTabIntroduction']", "?/?/tabpage[@automationid='RxTabIntroduction']", 30000, null, "0b2a0aa8-5258-4e19-9131-3f6fcd33cbae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("128da318-9aeb-4bbc-9f57-07cc8498df12")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("128da318-9aeb-4bbc-9f57-07cc8498df12")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("f273fc3e-9801-4934-80a1-0890d27339d9")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("f273fc3e-9801-4934-80a1-0890d27339d9")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction item.
            /// </summary>
            [RepositoryItem("0b2a0aa8-5258-4e19-9131-3f6fcd33cbae")]
            public virtual Ranorex.TabPage RxTabIntroduction
            {
                get
                {
                    return _rxtabintroductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The RxTabIntroduction item info.
            /// </summary>
            [RepositoryItemInfo("0b2a0aa8-5258-4e19-9131-3f6fcd33cbae")]
            public virtual RepoItemInfo RxTabIntroductionInfo
            {
                get
                {
                    return _rxtabintroductionInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
